### ISSUE TITLE
Two questions: data generation and feature importance

### ISSUE THREAD

**Issue by hedgy123** [grobgl/fy_project#1]
Hi Georg,

  First, thanks for making your code available!  It's a really interesting approach to survival analysis.

   Can I ask you a couple of questions?

1. How do I generate the data?   All the notebooks seem to assume that there's a directory called "data" with a bunch of .pkl files in it, but the directory is not there on your github.

2. Is there a way to estimate feature importance in this approach?

   Thank you!

**Comment by grobgl** [comment]
Hi, I'm afraid I don't have particularly exciting answers for you.
1. ASOS have declined to make the dataset publicly available. If you're interested, I can give you some ideas about the shape of the input data.
2. I did not look into this topic for this particular approach but I suspect there are applicable methods for feature importance in RNNs/LSTMs.
